### ISSUE TITLE
Building a specific map on windows 10 results in system crash

### ISSUE THREAD

**Issue by LuckyStripe** [Garux/netradiant-custom#100]
I've been trying to rebuild dna.pk3 on windows 10, however during building netradiant crashes my system completely (Blackscreen, postcode 00, and to recover I have to powercycle the PSU). 

The crash occures on:
  - netradiant precompiled
  - netradiant-custom precompiled
  - netradiant-custom compiled from source with msys2 & minGW64
  
I also tried compiling it on my laptop with arch linux (used the same precompiled xonotic 0.8.2 release, precompiled netradiant version, copied my xonotic data dir), there it does not crash and compiles as expected.

I can't see anything in the build log hinting at a reason for the system crash.
  Here is a log of one of the failed/crashed builds [radiant.log](https://github.com/Garux/netradiant-custom/files/8411107/radiant.log)
 
  And the dna.pk3 in case it is needed [dna.zip](https://github.com/Garux/netradiant-custom/files/8411119/dna.zip)

I have also found that:
  - Building dna with bsp mode succedes without a crash.
  - Also tried to build some other maps without problems

**Comment by Garux** [comment]
Tried building this, some issue:
```
WARNING: Couldn't find image for shader textures/trak5/ceil1a
WARNING: Couldn't find image for shader textures/evil_lights/rlight_a
WARNING: Couldn't find image for shader textures/evil3_floors/t-flr_oddtile_cln
WARNING: Couldn't find image for shader textures/evil6_lights/e6v_light
```

builds:
```
"C:/ok/install/q3map2.exe" -v -connect 127.0.0.1:39000 -game xonotic -fs_basepath "c:/_/Xonotic/" -fs_homepath "c:/_/Xonotic/" -fs_game data -bsp -meta -keeplights -maxarea -samplesize 8 -mv 1000000 -mi 6000000 "c:/_/Xonotic/data/maps/dna.map"
...
Writing c:/_/Xonotic/data/maps/dna.srf
Writing c:/_/Xonotic/data/maps/dna.bsp
Wrote 1.4 MB (1500236 bytes)
        1 seconds elapsed
```

As far as bsp preset works, my suspicions point to -maxarea, was noticed as problematic before.

**Comment by LuckyStripe** [comment]
I forgot to mention the crashes happen on the `Final` build options.

I'm still trying to figure out if this is just a problem with dna or if I'm doing something wrong here. Nevertheless I belive there is still an issue in netradiant itself, since the system should not crash. There should be an error & abort of the build. If I can pin-point the cause I guess I should move this issue to the official netradiant repo since it seems its not a problem of custom

**Comment by Garux** [comment]
Alright, my try shows args of final preset, same as yours.
This system uses no exceptions, so crash is just crash.
Way to debug is to build debug build and run problem case under debugger (i use vscode with its gdb support in windows).
Your crash symptoms are pretty uncommon though, can't it be e.g. file access in broken drive area?

**Comment by LuckyStripe** [comment]
Thanks for the suggestion, I'll try debugging next. I think the filesystem being the cause is unlikely since the drive as well as the other components are brand new and no issues are reported anywhere else.

**Comment by LuckyStripe** [comment]
Found out at a later point that my power supply was faulty and causing crashes to black screen on sudden power consumption peaks. Unfortunately don't have time to verify this currently, but it was very likely the culprit so I'll close this issue.
