### ISSUE TITLE
Generic Mode for NetRadiant Custom

### ISSUE THREAD

**Issue by HeadClot** [Garux/netradiant-custom#104]
Would it be possible to get a generic config for NRC? Similar to how Trench Broom handles its generic mode. This would be really useful for people making their own games with Net Radiant Custom but do not want to use trench broom. Currently Trench broom is the only quake level editor that has a Generic Mode. 

Here is what I would like to see in a NRC generic mode -
- Support for the Quake 1 valve 220 .map format
- The ability to use widely used image files such as .jpeg, .png, etc. for texturing maps opposed to Quake 1 .wad files.

To give some context about why I want this - I use [HammUEr](https://nte.itch.io/hammuer) to import levels from Trench broom to Unreal Engine. I then add the various game logic, props, etc. inside Unreal Engine. 

This would also be useful for tools such as RealTimeCSG for Unity with its .map importer [plugin](https://github.com/Quixotic7/RCSGQuake1MapImporter) and the [Qodot plugin](https://github.com/QodotPlugin/qodot-plugin) for Godot engine.

**Comment by eGax** [comment]
Just throwing this out there. Anyone can make a game support file addon for NRC to achieve what you are looking to do. Just look at the existing supported games for examples.

**Comment by HeadClot** [comment]
> Just throwing this out there. Anyone can make a game support file addon for NRC to achieve what you are looking to do. Just look at the existing supported games for examples.

Hey - How would I go about doing this? I am more than willing to make a PR for a NRC generic mode if I knew what to look for and do.

**Comment by wongit** [comment]
If you're not playtesting your game in a quake engine then you can use q3 as your game to see textures/ in editor. NRC has valve 220 map format for both q1 and q3 but I think HammUEr screwed UVs when I tried.

**Comment by Garux** [comment]
QL gamepack matches the wishlist: tga, jpg, png, textures go to baseq3/textures/yourfoldername/, valve220 selectable via preferences.brush.new map brush type.
Except this flavor of 220 stores face flags, which may be pa problem, fixable by `maptypes="mapq1"` in `gamepacks\games\quakelive.game`.

**Comment by HeadClot** [comment]
> QL gamepack matches the wishlist: tga, jpg, png, textures go to baseq3/textures/yourfoldername/, valve220 selectable via preferences.brush.new map brush type. Except this flavor of 220 stores face flags, which may be pa problem, fixable by `maptypes="mapq1"` in `gamepacks\games\quakelive.game`.

Hey thanks for the tips everyone. I have an initial version of the `generic.game` profile working. I am going to make a simple map and export it to unreal engine to see what else I need to do.

**Comment by eGax** [comment]
I have a generic game profile already you can have.

**Comment by eGax** [comment]
[generic-NRC.zip](https://github.com/Garux/netradiant-custom/files/8792195/generic-NRC.zip)

**Comment by HeadClot** [comment]
Thank you so much @eGax for this. Will be using this for the base of my PR :)

**Comment by Garux** [comment]
`Godot` gamepack included in [Releases](https://github.com/Garux/netradiant-custom/releases) serves as 'generic' gamepack.
