### ISSUE TITLE
Odd red lines in between the "TB Lines"

### ISSUE THREAD

**Issue by Ecl1pseGST** [Garux/netradiant-custom#116]
Hello. The other day when mapping for Q4 i somehow enabled these red lines that are spaced with the grid, within the "guide lines" or "trenchbroom lines". It's very annoying visually. I couldn't find a setting in Preferences that fixes it. I was one version behind, so i deleted my install and installed the latest version. Still happening. Tried "clean" under preferences, still happening. It does it for all games i map for as well, not just Q4, also Q3 and RTCW. 
![image](https://user-images.githubusercontent.com/102322421/192154261-ce51f665-efbd-4e6e-975f-507eebc14065.png)

**Comment by Garux** [comment]
Option is view.show.3d workzone.
Problem was noticed with Intel video drivers before, apparently `glEdgeFlagPointer` is bugged there.

**Comment by Ecl1pseGST** [comment]
Interesting, i'm running an RX480 on Adrenaline 22.8.2, but i appreciate the speedy response, thanks!
