### ISSUE TITLE
Arbitrary Rotations needs more than 2dp precision or cracks appear

### ISSUE THREAD

**Issue by jsbaboon** [Garux/netradiant-custom#12]
I'm so happy to discover this custom radiant (2018-05-16 v3.1.0 build 9.17.10.4459). Solved major texture mapping issues and bug/crashes from Ingars radiant, but was so disappointed to find all in vain since I need more than f.xx Arbitrary Rotations precision for my precision geometrical maps. This was never an issue before. Please recompile a version that allows greater precision (f.xxx at the VERY least). I would if do it myself if I could. This would then be the perfect mapping program. Thanks for the good work!

**Comment by Garux** [comment]
Hey, there is a trick to get full precision: using Enter key to apply rotation :)  
Thanks for the notice, now ic the reason of behavior change, this fix:
`	* Rotate dialog: fix: new value in focused field wasn't taking in account on Enter`  
I'll check what would be possible to do to get both candies

**Comment by Garux** [comment]
This solves button case for me:  
https://github.com/Garux/netradiant-custom/commit/07bc303c2d5e8c5f691a1b86318d8c81b2e5f89d
