### ISSUE TITLE
Viewports seem offset and not fit to the actual viewport

### ISSUE THREAD

**Issue by ensiform** [Garux/netradiant-custom#121]
![image](https://user-images.githubusercontent.com/997399/200093471-90731964-21c9-436a-bb25-1402a9269a79.png)

**Comment by Garux** [comment]
To concretize this is X11 and scaling is done via `QT_SCALE_FACTOR=1.25`, which if for dpi unaware apps. So entire picture is sort of upscaled with nearest filter, except of openGL viewports.

**Comment by Garux** [comment]
https://github.com/Garux/netradiant-custom/commit/15ca7060372cb782be3e1afd7f95cba8926d8ac2 supposedly fixes this.
