### ISSUE TITLE
Mouse look in 3d viewport does not work in wayland

### ISSUE THREAD

**Issue by theangrygrunt** [Garux/netradiant-custom#126]
Behavior: Whenever I right click into the 3d viewport and attempt to move the cursor, the error message `QT WRN qt.qpa.wayland: Setting cursor position is not possible on wayland` floods the console. When I right click out, `QT WRN default: This plugin supports grabbing the mouse only for popup windows` appears. 

Radiant version is 1.6.0n-git-48a6cf3c9

**Comment by Garux** [comment]
Yeah, wayland has no key features to be usable.
Solution of wayland issues is to use xwayland by running as 'QT_QPA_PLATFORM=xcb ./radiant.x86_64'

**Comment by theangrygrunt** [comment]
That fixed the issue, ty!
