### ISSUE TITLE
Feature Request: Texture with alpha channel

### ISSUE THREAD

**Issue by EugenyP** [Garux/netradiant-custom#129]
Texture alpha channel not showing in Camera window

![Clip2net_230129211423](https://user-images.githubusercontent.com/5616093/215332332-9ef254ce-d834-4cf2-a3ff-f38872fc4f57.png)

**Comment by Garux** [comment]
You need to request this explicitly by qer_alphafunc or qer_trans in your shaders.

**Comment by EugenyP** [comment]
> You need to request this explicitly by qer_alphafunc or qer_trans in your shaders.
oh, it working
thank you!
