### ISSUE TITLE
Cannot open a map if the file path contains a directory with accentuated characters

### ISSUE THREAD

**Issue by Spike29** [Garux/netradiant-custom#130]
Tested with the latest 20221212 release on Linux (from the provided zip).

If the file path contains a symlink or if a directory has an accentuated character (e.g `/home/user/développement/test.map`), the map won't open in NRC. There's no error dialog, the 2D and 3D viewports are just empty.
However, after closing then reopening NRC, some settings have been reset, like the interface layout, the grid + GUI themes and the mouse sensitivity (there's probably more).

Opening the same map with a "standard" file path works perfectly.

**Comment by Garux** [comment]
Editor and all the tools are ASCII only, UTF support is not to be done i think, as 1. it's *huge* rewrite 2. engines of supported games are mostly ASCII only, especially wrt internal strings 3. many 3rd party tools are ASCII only.

Symlinks were mentioned as working here https://github.com/Garux/netradiant-custom/pull/108. Standard functions resolve them afaik, but there may be side effects during specific operations.

Settings corruption is a pity, i guess parsing was broken by presence of UTF there in recent map path.

**Comment by Spike29** [comment]
Oops my bad, the parent directory of my symlink had accentuated characters, I didn't pay attention ^^  
I confirm that symlinks are otherwise working.

Thanks for the explanation regarding the missing UTF support.
