### ISSUE TITLE
Old Xonotic default build menu

### ISSUE THREAD

**Issue by Spike29** [Garux/netradiant-custom#131]
`netradiant-custom-20221212/gamepacks/xonotic.game/default_build_menu.xml` is an old version of the build menu.

The latest one is https://gitlab.com/xonotic/netradiant-xonoticpack/-/blob/master/xonotic.game/default_build_menu.xml.

Of course it's possible to replace it manually, but it would be nice to include the new Xonotic build menu in the next NRC release :)

**Comment by Garux** [comment]
Will include, adjusted it greatly:
* [ExtraQ3map2Args] not supported/needed, extra args get applied w/o it
* no -fastmeta, normal -meta is faster by an order of magnitude in NRC, no cheap hacks are needed
* -keeplights is excess? is default for xonotic https://gitlab.com/xonotic/netradiant/-/blob/master/tools/quake3/q3map2/game_xonotic.h#L76
* -mv 1000000 -mi 6000000 already bumped in game cfg https://gitlab.com/xonotic/netradiant/-/blob/master/tools/quake3/q3map2/game_xonotic.h#L59; doubtfully that 6M of indices may be practically needed or shall bump in cfg (if engine supports this); constructing such a surface though will take a couple of infinities with old meta algorithm
* -nobouncestore doesn't exist in NRC, might be worthy to port considering big lightmaps
* -fastallocate - is fast by default in NRC

-fill in fast presets is suspicious, operation is slow kinda
[default_build_menu.zip](https://github.com/Garux/netradiant-custom/files/10679557/default_build_menu.zip)

**Comment by Garux** [comment]
ported -nobouncestore commit https://github.com/Garux/netradiant-custom/commit/2c947b7e9532a4e915dd488bb79b995836f15e53, readded it to build menu too

**Comment by Spike29** [comment]
Hello,

We disabled light backsplash on our default build menu (with `-backsplash 0 0`) because it caused issues on some maps, see https://gitlab.com/xonotic/netradiant-xonoticpack/-/merge_requests/9.

Could you add this change to future pre-compiled versions of NRC?

It would still probably be worth adding a second `Final: -bounce 8 -dirty (new Xonotic's default)` build entry with backsplash enabled (that's what I do on my end).

**Comment by Garux** [comment]
Ok, will do.

**Comment by Spike29** [comment]
Thanks!
