### ISSUE TITLE
Region compile leaks if no entities in region and camera is inside a structural brush

### ISSUE THREAD

**Issue by Aciz** [Garux/netradiant-custom#132]
If you try to compile a region but have 0 entities, and your camera is currently inside a structural brush, the map will leak.

![image](https://user-images.githubusercontent.com/14221121/221274481-0831d5bf-8a2e-4d9e-8a43-cdfb4125d28b.png)

**Comment by Garux** [comment]
This is expected behavior. Compiler relies on entities placement to determine which side of map volume is playable; the only entity in this case is player spawn, placed at camera location.

**Comment by Aciz** [comment]
How does it make sense though, considering the outer walls are supposed to be structural? The map shouldn't leak in that case. Also it seems to only happen if the structural brush you're inside of is touching the void, which would suggest that leak testing is done before the region walls are placed, which sounds like a bug to me.

**Comment by Garux** [comment]
No, this is how compiler's FloodEntities algorithm normally works
![image](https://user-images.githubusercontent.com/1734117/222363994-d66a678b-4642-49ab-9dd7-5fdcfae6e054.png)
You can evaluate mapname.reg, this is what is sent to compiler.
