### ISSUE TITLE
OBJ models have a different rotation when the map is loaded between NR and NRC

### ISSUE THREAD

**Issue by FrancescoBis** [Garux/netradiant-custom#137]
I tested it with MD3 models and they have the same rotation when the same map is loaded in both NetRadiant and NetRadiant-Custom. While OBJ models have a different rotation.

**Comment by Garux** [comment]
This is intentional https://github.com/Garux/netradiant-custom/commit/034f06f18d4dc3615f4211ab0351ebf81f44e7f5 to match most of 3D modelling software.

**Comment by Garux** [comment]
Yes.
