### ISSUE TITLE
[Feature] Make Filter -> Botclips include common/botdonotenter

### ISSUE THREAD

**Issue by NeonKnightOA** [Garux/netradiant-custom#14]
Sometimes, when working on a map, it irkes me a bit not being able to hide both common/botclip and common/botdonotenter brushes. I can use Filter -> Botclips to hide the former, but not the latter.

It would be really cool if Filter -> Botclips could also hide these brushes. Or if an additional Filter -> Botdonotenters command could be added.

**Comment by Garux** [comment]
Sounds reasonably, added:  
https://github.com/Garux/netradiant-custom/commit/c611be157a14593c731a2514b2b772b542e988d6  
`textures/common/donotenter`, right?  
Are you aware of methods to hide such sort of things, like `m3 on brush, shift+a, h` or `m3 on brush, shift+a, i, ctrl+shift+r`?

**Comment by thedarkb** [comment]
I was talking in #xonotic on Freenode the other day and apparently the main branch of NetRadiant needs gcc7 to build. The vast majority of Linux distros are still on gcc6, and according MinceR, it was "modernised" with the intention of cutting support for SystemD based distros. Will this branch continue to build on gcc6?
