### ISSUE TITLE
"Shader not found" despite qer_editorimage specified

### ISSUE THREAD

**Issue by TomArrow** [Garux/netradiant-custom#142]
![shader not found](https://github.com/Garux/netradiant-custom/assets/6640421/73fb14d6-9c8b-4077-b27d-fb7f68acb065)
This shader is found by the editor through the shader file which is in the shaderlist.txt, but it doesn't display it as a texture.

This is the shader:
```
textures/rift/rock3_phong
{
	q3map_shadeangle	98
	qer_editorimage	textures/yavin/rock3
	q3map_nonplanar
	q3map_splotchfix
	q3map_forcemeta
    {
        map textures/rift/rock3
        rgbGen identity
    }
    {
        map $lightmap
        blendFunc GL_DST_COLOR GL_ZERO
        rgbGen identity
    }
}

```
I noticed the qer_editorimage points at a different folder which is likely an oversight by the developers however textures/yavin/rock3 exists and is in fact the same texture as textures/rift/rock3, but it is not displayed. It's a 1024x1024 jpeg image.

Any clues to what's the problem here?

Edit: It displays fine ingame, but in the editor it's just all blue/"shader not found". Also, if important, the game is Jedi Academy.

**Comment by TomArrow** [comment]
On a side note, the font is very small in the new netradiant version on above HD dissplay, is there a way to fix it? I checked preferences but don't see font size. Makes it hard to read some stuff depending on color.

**Comment by TomArrow** [comment]
Nevermind I did indeed not have it in shaderlist.txt. I assumed it would be by default.

**Comment by Garux** [comment]
Here are color and font adjustments
![image](https://github.com/Garux/netradiant-custom/assets/1734117/96c9adf7-33db-4d24-9e5d-0fa8d32fdc99)
