### ISSUE TITLE
Texture keyboard shortcuts not working with Surface Inspector window open

### ISSUE THREAD

**Issue by negke** [Garux/netradiant-custom#147]
Several texture-related keyboard shortcuts don't seem to work when the Surface Inspector window is open, the ones using arrow Up or Down and PageUp/PageDown. TexScaleUp/Down, TexShiftUp/Down, TexRotateClock/Counter. Once the window is closed, they do. TexScaleLeft/Right and TexShiftLeft/Right work as intended in both conditions. I'm using the floating window layout if that's relevant. Must have been introduced in one of the last two builds, possibly some GTK thing?

**Comment by Garux** [comment]
Do you mean with Surface Inspector having focus? I actually filter some keys needed for GUI elements functioning https://github.com/Garux/netradiant-custom/blob/07f66499dd6894297f677057dfb05579b6954530/radiant/surfacedialog.cpp#L619
Also doing this in other nonmodal dialogs.
Would need to be more precise there to get named shortcuts working.

**Comment by negke** [comment]
Yes, I mean when the widow is focused.

**Comment by Garux** [comment]
Gotta work now.
