### ISSUE TITLE
(Feature request) Take into account currently used color theme for rendering entities in the 2D view.

### ISSUE THREAD

**Issue by RazielZnot** [Garux/netradiant-custom#149]
I always use Black and Green theme but it has one issue, using func_group or some other entities colored as black makes their wireframe invisible in the 2D view which is very annoying. I understand that this color is set in the DEF file but the editor shouldn't use it straight away, at least turn it negative or something?

**Comment by Garux** [comment]
I think it's up to ent def composer to not use black color, which collides with world while white bg and bg while dark bg.
If we automatically alter colors, they will likely collide something else, e.g. entity or grid; And entity color inconsistency is not cool in general.

**Comment by RazielZnot** [comment]
The problem is that the average user doesn't know about such details. Back in the day, when I only started using GtkRadiant, I had no idea why Black and Green theme makes some entities invisible, so I had no other choice but to switch between themes, which defeats the purpose of having them. Comparing the color of the entity to the current color of the background shouldn't be an issue, if the background is black and the entity is black then turn the entity negative, or turn them all negative without comparison just check which theme is currently in use, then black will turn white, orange - blue, red - cyan, it will look fine on black background.

**Comment by Garux** [comment]
I have just explained why this is not optimal idea. Let's fix those .defs instead to improve UX.

**Comment by RazielZnot** [comment]
Most users have no idea how to edit the DEF file, this is the point and I don't care about my own convenience here. I may fix it for myself, but what about the rest of the users? If the editor requires manual editing of the DEF file, then I see this as a design flaw of the editor, because it looks just fine when used with the default color theme.

**Comment by Garux** [comment]
Fix for yourself and share, so i'll include it for others.

**Comment by RazielZnot** [comment]
Too many of them...
