### ISSUE TITLE
Default texture scale is limited to 2 decimal places

### ISSUE THREAD

**Issue by Rev3n4nt** [Garux/netradiant-custom#152]
I need to use textures that 8 times bigger, so default texture scale should be 0.125;
Default texture scale now is limited to 2 decimal places (0.12 only).
Because of that I need to adjust scale everytime I put a new texture on a brush.
![image](https://github.com/Garux/netradiant-custom/assets/3937419/bf33aacd-9548-44d2-acad-aa37d765a20e)

**Comment by Garux** [comment]
Ouch, nice catch, this is overlook.
