### ISSUE TITLE
quakelive support?

### ISSUE THREAD

**Issue by MatthewHannigan** [Garux/netradiant-custom#154]
HI Garux and all, nice radiant variation.

Is quakelive supported?  The README mentions it but the startup doesn't offer it as an option.

Regards,
Matt

**Comment by Garux** [comment]
Oops. i accidentally this file, while fixing .bsp import. Thank you for repot!
[quakelive.zip](https://github.com/Garux/netradiant-custom/files/12837463/quakelive.zip)
