### ISSUE TITLE
Can I make some kind of terrain?

### ISSUE THREAD

**Issue by CuteNoiRe** [Garux/netradiant-custom#155]
I know about the existence of EasyGen, I would like to know if it is possible to make a mesh of 20x20 brushes and conveniently change their vertices to create something like a terrain, as is done in Trenchbroom?

This is my favorite editor and its HL support is impressive!

**Comment by Garux** [comment]
Yes you can. Most of needed knowledge is in menu.help.mouse shortcuts.

**Comment by CuteNoiRe** [comment]
I don't quite understand, can you explain in more detail?

**Comment by The-Gig** [comment]
I guess you may search for some quake3 terrain tutorials, like these <https://web.archive.org/web/20140820044241/http://www.simonoc.com/pages/articles.htm>
