### ISSUE TITLE
Half-Life: changing the light entity position by dragging trims the _light property value

### ISSUE THREAD

**Issue by ghost** [Garux/netradiant-custom#156]
In Half-Life, the _light property for light source entities stores both the light color and light intensity, in a form of RGBA value separated for spaces, for example "255 255 240 65"
![image](https://github.com/Garux/netradiant-custom/assets/132096644/99257962-d9a9-4998-8159-d705be2ae0af)
![image](https://github.com/Garux/netradiant-custom/assets/132096644/8fbb0a15-df94-4f7f-9ddf-06c01a7a6e4f)
But when I drag the entity around, the value gets trimmed to just the R value ("255 255 240 65" > "255"). The weirdest thing is that this only happens when I drag the entity with a mouse, not when I change the entity origin value. TrenchBroom doesn't appear to have such behaviour. Is it a confuguration issue or something else that needs to be fixed?

**Comment by Garux** [comment]
This is side effect of feature about adjusting light power by mouse drag.
Would need to look into this, for HL with unusual _light key content it's probably the best to disable it entirely.

**Comment by purpletheblaze** [comment]
> This is side effect of feature about adjusting light power by mouse drag. Would need to look into this, for HL with unusual _light key content it's probably the best to disable it entirely.

If that is so, maybe it's better to be disabled for Half-Life altogether, as I don't think an easy mouse drag control of HL's weird RGBI value for lights can be implemented
