### ISSUE TITLE
(q3map2) Allow compiling CONTENTS_JUMPPAD in WolfET

### ISSUE THREAD

**Issue by ovska** [Garux/netradiant-custom#161]
Possibly this isn't the correct place for this request, but I want to compile contents with contentparms `CONTENTS_JUMPPAD` (0x00080000). This flag is recognized here and there, but there doesn't seem to be a matching shader keyword in the compiler.
This flag is used for content-specific suppression of portalgun in ETJump, but it seems like there has never been a way to actually compile it.

https://github.com/Garux/netradiant-custom/blob/e9459b79d836dbec85e8147d4f26593dcab7dede/tools/mbspc/qcommon/surfaceflags.h#L46
https://github.com/Garux/netradiant-custom/blob/e9459b79d836dbec85e8147d4f26593dcab7dede/tools/quake3/q3map2/games.cpp#L359

**Comment by ensiform** [comment]
If you need to use custom contents or surface flags that aren't part of the main game. you use the custinfoparams feature that's been around in q3map2, for like ever.

https://en.m.wikibooks.org/wiki/Q3Map2/BSP

**Comment by ovska** [comment]
Thanks. I was unaware of this feature and it does indeed solve my problem!
