### ISSUE TITLE
Feature Request: Entity search by key/value

### ISSUE THREAD

**Issue by ensiform** [Garux/netradiant-custom#162]
Would be cool to be able to list and find matching entities by key and or (partial) values. I was just trying to remove some entities that had a specific game mode option "1,9" in ETF and I figured it would be cool to be able to find all without using external text app that can then be selected from the search window.

**Comment by Garux** [comment]
![image](https://github.com/Garux/netradiant-custom/assets/1734117/f0a1435b-2e1c-48bc-942b-a14a74a0132c)
these 3 buttons do it
