### ISSUE TITLE
[Feature request] Draw light radius on negative lights

### ISSUE THREAD

**Issue by Aciz** [Garux/netradiant-custom#163]
Negative lights are really useful for making "fade to black" spots in maps, but they currently require a bit of trial and error to get right when it comes to the light intensity, since there's no indication on the radius of the light. You can work around this ofc by using regular positive light first to adjust the light power to desired value, before making it negative, but it would be nice to have the radius drawn and not have to resort to this. For negative lights, the radius could for example be drawn without the fill, so only the radius "rings" would be visible.

![image](https://github.com/Garux/netradiant-custom/assets/14221121/49277ba7-30ad-476d-9b27-7ce1e6383ae4)

**Comment by Garux** [comment]
Drawing radiuses, at least w/o special representation, seems worthy, as long as you can't occasionally make value negative.
