### ISSUE TITLE
:q3map Suffixes do not work with External Lightmap hack

### ISSUE THREAD

**Issue by tehSandwich** [Garux/netradiant-custom#165]
### **Using:**
- Current Dev Build (Sept. 20 2023)

### **Description:**
So I've been using textures with :q3map suffixes to have metalsteps without having to bloat my shader file with the long hand version. They work perfectly fine with internal lightmaps (and I assume external lightmaps with proper support) but it turns out that it doesn't work with the external lightmap hack, they don't get transfered into the new shader file and instead, surfaces with those textures just get the vertex lighting fallback.

### **Expected Result:**
This but with higher resolution lightmaps:
![2024_01_30-15_41_49-750](https://github.com/Garux/netradiant-custom/assets/4885422/f6e6d79a-7c48-489b-84e6-00cbacd2156d)

### **Actual Result:**
Those surfaces fallback to vertex lighting.
![2024_01_30-15_39_35-999](https://github.com/Garux/netradiant-custom/assets/4885422/1d725625-d3c5-4c3a-ba77-774eb9588ee3)

**Comment by Garux** [comment]
Thank you for the report!
