### ISSUE TITLE
Unmonitored compilers cannot start and compile

### ISSUE THREAD

**Issue by tehSandwich** [Garux/netradiant-custom#166]
### Using:
* Current Dev Build (Feb. 3 2024)
* Windows 10

### Description:
At the moment, compilers that aren't or cannot be monitored cannot be run from radiant due to cruft appended at the end of each command.

This is what comes from the .bat file it generates:
`"D:/netradiant-custom-win64/netradiant-custom-20240203/mbspc.exe" -bsp2aas "D:/Quake3/baseq3/maps/mapfile.map" -forcesidesvisible -optimize > ""`
`PAUSE >> ""`

Removing the `> ""` makes it work like normal.

**Comment by Garux** [comment]
Good catch! Can workaround the problem by this setting now
![image](https://github.com/Garux/netradiant-custom/assets/1734117/9c34a136-7243-4b3e-add5-233e85f96bd8)
