### ISSUE TITLE
assertion failure - 22040208

### ISSUE THREAD

**Issue by pinickitty** [Garux/netradiant-custom#168]
on first run the latest version 22040208 is giving the following error
![assertion](https://github.com/Garux/netradiant-custom/assets/157492047/21a1dec2-5248-40d7-a0c7-3d2e574f6ecb)

error is in screenshot

**Comment by Garux** [comment]
Aha, problem is spotted due to this fix https://github.com/Garux/netradiant-custom/commit/0ead65d10bdf49084aeb01daa32f706961949198
Shall fix problem ent defs.

**Comment by Garux** [comment]
Fixed .ent of ET & ZEQ2lite wrt this issue, rebuilt the build https://github.com/Garux/netradiant-custom/releases/tag/latest
