### ISSUE TITLE
No icons when compiling in Windows with msys2

### ISSUE THREAD

**Issue by Pipexlul** [Garux/netradiant-custom#17]
Windows 10 just followed all instructions for Win32 - MSYS2 64 bit.
The result is this:
![radiant_2018-11-06_16-48-10](https://user-images.githubusercontent.com/44515058/48089699-da3c2280-e1e3-11e8-8eea-6959e06c86c0.png)

The splash screen is also a missing icon, I checked and all the icon files are correctly placed under bitmaps/ folder but they don't display in the program.

**Comment by wongit** [comment]
I had the same issue a few months back and found replacing \msys64\mingw64\bin\libgdk_pixbuf-2.0-0.dll with the one included in the 64bit release fixed it.

**Comment by Garux** [comment]
Perhaps msys2 lib got borked or radiant is using deprecated function.  
At least it was working with fresh msys2 libs year ago, got to recheck.

**Comment by Garux** [comment]
Issue is totally legit, as new gdk-pixbuf is using optional external modules, changed script copies them too.
