### ISSUE TITLE
(Feature Request) Clip brushes by face selection

### ISSUE THREAD

**Issue by sinewavey** [Garux/netradiant-custom#170]
https://github.com/Garux/netradiant-custom/assets/90056029/466ee8f6-8104-40c6-911b-2eacd73750b7

See attached video.

In short: when selecting a face, one may translate it (to adjust the size of the brush as normal, of course) or optionally apply a modifier key to _clip_ the brush as well.

The process ends with both brushes still selected, and can be further compounded.

**Comment by Garux** [comment]
This is called 'extrude inside', see extrude shortcut in menu.Help.General.Mouse Shortcuts

**Comment by Garux** [comment]
Right, it's available in default manipulator mode. Other manipulators are focused on doing their niche stuff.
Face thing is not a tool, it's component mode. Most of manipulators are applicable in all component modes.
Note uses of extrusion: https://garux.github.io/NRC/#Extrude%20brush%20face%20inside,%20mass%20extrusion%20of%20selected%20brush%20faces%20(ctrl%20+%20alt%20+%20m1)
https://garux.github.io/NRC/#Some%20editing%20techniques
https://garux.github.io/NRC/#Creating%20curve%20of%20brushes%20(extrude,%20merge)
