### ISSUE TITLE
Add mbspc face-to-brush with best merge faces 

### ISSUE THREAD

**Issue by karakakarkarkar** [Garux/netradiant-custom#171]
Possible to merge all faces(with same parameters) and then split to convex faces for decompile? 

I think this can decrease output brushes count? 

Also for face-to-brush need only one vertex (for example centroid of face - 4.0f offset) 

https://github.com/UnrealKaraulov/newbspguy/blob/892107e076eb68cc625ec660222ea1055b419d7a/src/bsp/Bsp.cpp#L9353

**Comment by Garux** [comment]
Brush per face decompiler exists, it's less usable result.

**Comment by karakakarkarkar** [comment]
@Garux yes but maybe can be improved by adding 

0. Remove faces with CONTENT_SKY and CONTENT_SOLID 
1. 'merge all faces' 
2. Split for convex faces

This can give better results and more small output brush count. 

And generate one back point for one brush with center offset, front textured, back textured for example with NULL when possible (just one plane for every edge + back_vert) , but very bad that no special texture for skip back faces and generate nodes/clipnodes for front face)

**Comment by Garux** [comment]
Ic no point in reinventing the wheel https://github.com/twhl-community/HalfLife.UnifiedSdk.MapDecompiler/issues/31, while it doesn't produce somewhat similar to original brushes anyway.
Pull request would be highly appreciated ofc!

Side note: pyramidal brushes are expected to be way less efficient in bsp, compared to using axial planes.

**Comment by UnrealKaraulov** [comment]
@Garux how to use face-to-brush algorithm in mbspc ? or this only tree decompiler ?

**Comment by Garux** [comment]
only tree decompiler
