### ISSUE TITLE
The Surface Inspector "texture" field grabs the keyboard focus on Linux

### ISSUE THREAD

**Issue by Spike29** [Garux/netradiant-custom#184]
Small inconvenience: when you open the SI under Linux, the "texture" field grabs the keyboard focus.
If you open the SI and immediately try to use a global shortcut ("T" or "O" or whatever), this won't work and you'll type characters in the "texture" field instead.

This was apparently fixed on Windows: https://github.com/Garux/netradiant-custom/commit/a99892751b869186743fc4d2734db67e9dd70b41

**Comment by Garux** [comment]
Try this, works in Ubuntu.

**Comment by Spike29** [comment]
Thanks!
It also works on my end.
