### ISSUE TITLE
Choices also merge from FGD

### ISSUE THREAD

**Issue by sinewavey** [Garux/netradiant-custom#192]
I have the following line in my FGD:

![image](https://github.com/Garux/netradiant-custom/assets/90056029/56e66324-0756-4d4a-8f86-de9012f866ab)

I've tried a few different combinations including 0 and 1, "Yes" and "No', etc.
However, it looks like keys end up colliding here as well like spawnflags regardless of the above tweak.

![image](https://github.com/Garux/netradiant-custom/assets/90056029/95ce44bd-e868-428a-8d4c-efef9fbeda62)

Expected behavior shown in TrenchBroom with the same exact fgd:

![image](https://github.com/Garux/netradiant-custom/assets/90056029/92d1c22e-38cb-4e9d-a6b7-f0f1b4d5e6be)

Is this intentional?

**Comment by Garux** [comment]
I'm looking at `halflife.fgd` and e.g. in `@BaseClass base(Targetname,Global) = Breakable` no collision of choices occurs 🤔

**Comment by Garux** [comment]
ok, problem is triggered by equal 'qwe' strings, empty in your case

```css
@BaseClass color(123 123 123) size( -8 -8 -8, 8 8 8 ) = Breakable
[
	material(choices) : "qwe" =
	[
		2: "Glass"
		3: "Wood"
	]
	explosion(choices) : "qwe" =
	[
		0: "Random"
		1: "Relative to Attack"
	]
]

@PointClass base(Breakable) = func_breakable : "Breakable Object" 
[
]
```

**Comment by sinewavey** [comment]
Excellent - thank you! That closes this - we'll handle it on our side

**Comment by Garux** [comment]
This is bug tho, somewhere matching is done by long name, while should use key name.
