### ISSUE TITLE
User-selectable material for autocaulk

### ISSUE THREAD

**Issue by SirYodaJedi** [Garux/netradiant-custom#209]
A few months ago, while mapping for Deathmatch Classic (GoldSrc), I ended up using NRC's autocaulk feature to automatically set a bunch of interior faces to CONTENTEMPTY to work around a lighting compiler quirk. I had to batch-replace the `common/caulk` to `CONTENTEMPTY` afterward, which made me realize that the tool is hardcoded to always use the material `common/caulk`:
https://github.com/Garux/netradiant-custom/blob/7ee5bfdad8baf3b3d2748e36393415a210ca8a00/radiant/filterbar.cpp#L45

I imagine having the material be user-selectable would have benefits beyond my niche use-case, such as if a Q3 mapper wants to autocaulk a specific piece of geo as `common/nodraw` instead of `common/caulk` or something.

**Comment by SirYodaJedi** [comment]
I see it works for q1.game, applying `skip` instead of `common/caulk`, but I don't see where it's controlled.

**Comment by SirYodaJedi** [comment]
Updated the `hl.game` file, made common `.shader` files for VHLT, and cleaned up the cstrike FGD; feel free to trim as necessary.
[hl1gamepack.zip](https://github.com/user-attachments/files/16368053/hl1gamepack.zip)

**Comment by Garux** [comment]
Brilliant, thank you!
