### ISSUE TITLE
Item entities look wrong when the "model" key is left blank

### ISSUE THREAD

**Issue by Spike29** [Garux/netradiant-custom#210]
Hello,

A new key was recently added to several Xonotic item definitions ([among other changes](https://gitlab.com/xonotic/xonotic-maps.pk3dir/-/merge_requests/194)):
`<model key="model" name="model">model to use, leave blank to use the item's regular model</model>`

Item entities look wrong in NRC with this change and when the key is left blank:
![Copie d'écran_20240814_130800](https://github.com/user-attachments/assets/c5dced7b-10ff-4a3f-bcf7-3f8e267f3dfa)
In NR, the [the entity box](https://gitlab.com/xonotic/xonotic-maps.pk3dir/-/blob/master/scripts/entities.ent?ref_type=heads#L464) is shown instead, as expected:
![Copie d'écran_20240814_132347](https://github.com/user-attachments/assets/87d4ef96-b482-48c3-8007-af0f5fa469a6)

Is it possible to ignore this key for item entities, at least when it's left blank, and draw the box instead?

The size of the box in our entity definitions is the same as the size of the entity's bbox in the game, so it's very useful to draw it.

**Comment by ensiform** [comment]
Seems like a NR specific change you guys made, because since q3radiant days, items have always had to have a model defined or you get the null model iirc.

**Comment by Spike29** [comment]
Oh I see, thank you both for the clarification.

In NR (at least with the Xonotic gamepack), no models are displayed for item entities, even when the `model` key is set. Models are displayed for `misc_model` entities though, so it could be a bug in NR.

I've changed the key type to string and that seems to do the trick, thanks!
The items now look like boxes in NRC, but the model key is still respected in-game.

Since Xonotic mappers are used to items looking like boxes in Radiant, this is probably the best thing to do for now.
I'll update our entity definitions with this trick.

**Comment by Garux** [comment]
If you declare model key default, this will be box in NR and full fashioned preview in NRC :)

**Comment by Spike29** [comment]
Yes, I've thought about it, but the default models in question are probably to be found in the xonotic-data pk3dir, which is one of our [forbidden paths](https://gitlab.com/xonotic/netradiant-xonoticpack/-/blob/master/games/xonotic.game?ref_type=heads#L29).

I'm not sure why this path is forbidden and I'd rather not touch it for now :D

**Comment by ensiform** [comment]
> Yes, I've thought about it, but the default models in question are probably to be found in the xonotic-data pk3dir, which is one of our [forbidden paths](https://gitlab.com/xonotic/netradiant-xonoticpack/-/blob/master/games/xonotic.game?ref_type=heads#L29).
> 
> I'm not sure why this path is forbidden and I'd rather not touch it for now :D

Curious why you would have the base game assets excluded from your mapping sdk though. It's kinda important for rendering things like that.

**Comment by Spike29** [comment]
> Curious why you would have the base game assets excluded from your mapping sdk though. It's kinda important for rendering things like that.

Probably because data files are subject to change, and our armor models [were renamed at some point](https://gitlab.com/xonotic/xonotic-maps.pk3dir/-/merge_requests/196#note_2047525442).

Xonotic is an old project but hasn't hit a stable version yet so this is to be expected I guess.

And we would need to edit our models first so they look correct in Radiant:
![Copie_d_écran_20240814_204108](https://github.com/user-attachments/assets/23750176-a803-4564-81ec-cccba0936c3f)
