### ISSUE TITLE
gamepacks/oa.game - missing space before "-fs_basegame"

### ISSUE THREAD

**Issue by andreymal** [Garux/netradiant-custom#211]
I downloaded `netradiant-custom-20240309-linux-x86_64.7z` from GitHub and tried to make an OpenArena map, but got this error:

```
=== running build command ===
"/data/programs/netradiant-custom/q3map2.x86_64" -v -connect 127.0.0.1:39000 -game quake3
-fs_basepath "/usr/share/games/openarena/" -fs_game baseoa-fs_basegame baseoa -light -fast -filter -super 2 "..."

--- InitPaths ---
VFS Init: /home/andreymal/.q3a/baseoa-fs_basegame/
VFS Init: /usr/share/games/openarena/baseoa-fs_basegame/
VFS Init: /home/andreymal/.q3a/baseq3/
VFS Init: /usr/share/games/openarena/baseq3/

--- BSP ---
WARNING: Unknown option "baseoa"
WARNING: Unknown option "-light"
WARNING: Unknown option "-fast"
WARNING: Unknown option "-filter"
WARNING: Unknown option "-super"
WARNING: Unknown option "2"
```

This is because `gamepacks/oa.game/default_build_menu.xml` contains this:

`<var name="q3map2">"[RadiantPath]q3map2.[ExecutableType]" -v<cond value="[MonitorAddress]"> -connect [MonitorAddress]</cond> -game quake3 -fs_basepath "[EnginePath]"<cond value="[GameName]"> -fs_game [GameName]</cond>-fs_basegame baseoa</var>`

No space before `-fs_basegame`.

But the original https://github.com/NeonKnightOA/oagamepack doesn't have this option at all!

I removed `-fs_basegame baseoa` and everything works fine.

I don't know where this option came from in the release archive, but it needs to be fixed in the next release

(https://www.dropbox.com/s/b1xpajzfa6yjlzf/netradiant-custom-extra-gamepacks.zip has the same error)

**Comment by Garux** [comment]
Og gamepack uses `-game oa`
oa game was added in NR to solve previous `-fs_game baseoa` workflow issues:
 - unwanted `baseq3` loading
 - impossibility to use a mod of OA (`-fs_game somethingelse`)
I found duplicating entire game profile to solely alter basegame pretty excessive, thus added `-fs_basegame` switch.
Space is actually missing, thank you for report, shall add it 👍🏿

**Comment by Garux** [comment]
Fixed in latest build.
