### ISSUE TITLE
Make default path for games on Win in Program Files (x86)

### ISSUE THREAD

**Issue by x0rnn** [Garux/netradiant-custom#216]
Instead of Program Files. Most if not all idtech3 games are installed by default in Program Files (x86).

**Comment by Garux** [comment]
Makes sense.
Can you provide list of games, which surely reside at (x86)?
E.g. some maintained games apparently do not:
https://gitlab.com/xonotic/netradiant-xonoticpack/-/blob/master/games/xonotic.game?ref_type=heads#L7
https://gitlab.com/netradiant/gamepacks/tremulous-mapeditor-support/-/blob/main/games/trem.game?ref_type=heads#L5

**Comment by x0rnn** [comment]
Enemy Territory, RTCW, Quake 3, with others I'm not familiar.

**Comment by Garux** [comment]
Done for named games in latest build.
