### ISSUE TITLE
Xonotic gamepack updates

### ISSUE THREAD

**Issue by Spike29** [Garux/netradiant-custom#218]
Hello, is it possible to update the Xonotic gamepack in the next NRC build? (and also for users compiling NRC themselves with `DOWNLOAD_GAMEPACKS=allinone`) :)

[entities.ent](https://gitlab.com/xonotic/xonotic-maps.pk3dir/-/blob/master/scripts/entities.ent?ref_type=heads) and [xonotic.game](https://gitlab.com/xonotic/netradiant-xonoticpack/-/blob/master/games/xonotic.game?ref_type=heads) have recently been updated.

The changes to `entities.ent` are particularly significant:
- https://gitlab.com/xonotic/xonotic-maps.pk3dir/-/merge_requests/194
- https://gitlab.com/xonotic/xonotic-maps.pk3dir/-/merge_requests/196

**Comment by Garux** [comment]
Done, thanks for heads up!

**Comment by Garux** [comment]
Cool, noted 👍

**Comment by Garux** [comment]
Nice, grabbed.
