### ISSUE TITLE
[Bug] Implicitmap - & lightstyles write incorrect shader

### ISSUE THREAD

**Issue by Aciz** [Garux/netradiant-custom#220]
If a shader is using `implictMap -`, and is hit by a styled light, the lightstyle shader gets a texture map stage written without a `.tga` extension. Most modern engines handle this fine, but at least the original Wolf: ET 2.60b engine does not like this and won't properly resolve the textures.

As an example, the following stock Wolf: ET shader produces a broken lightstyle shader:

```
textures/metal_misc/ametal_m02
{
	surfaceparm metalsteps
	implicitMap -
}
```
```
lightstyle_bug/6711B43208ACB1852B6579E0706E3B38
{ // Q3Map2 defaulted (implicitMap)
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.7 2.5 0.6 4.69 // style 1
		alphaGen wave noise 0.7 2.5 0.6 4.69 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		// no .tga extension here
		map textures/metal_misc/ametal_m02
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}
```

But if the `implictMap -` was replaced with `implictMap textures/metal_misc/ametal_m02.tga`, the resulting shader would have `.tga` extension in the texture map stage. The issue only occurs when using `-` as the parameter (which grabs the shader name to be used as the texture).

I've not tested `implictMask/Blend -`, but I assume they're broken the same way.

I've attached a simple test map with broken shaders here.

[lightstyle_bug.zip](https://github.com/user-attachments/files/17556078/lightstyle_bug.zip)

**Comment by Garux** [comment]
Thank you for heads up!
