### ISSUE TITLE
Patches do not render in Doom 3 gamepack

### ISSUE THREAD

**Issue by Programme02** [Garux/netradiant-custom#223]
Patches render perfectly fine in the Quake 3 gamepack, but they do not in Doom 3's, both in the 2d and 3D views. I cannot select them in any panel after selecting another object. They are still saved in the .map file and appear in-game after compiling.

**Comment by Garux** [comment]
Any concrete example? Because they work as expected here.
Isn't it patch filter enabled on your end?

**Comment by Programme02** [comment]
:P That was exactly the issue. Thank you!
