### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Pollito001** [Garux/netradiant-custom#23]
When i trying to compile the teminal show me this error:

In file included from tools/mbspc/botlib/../qcommon/q_shared.h:104,
                 from tools/mbspc/botlib/be_aas_bspq3.c:32:
tools/mbspc/botlib/../qcommon/q_platform.h:184:3: error: #error ARCH_STRING should be defined by the Makefile
 # error ARCH_STRING should be defined by the Makefile
   ^~~~~
tools/mbspc/botlib/../qcommon/q_platform.h:309:2: error: #error "Architecture not supported"
 #error "Architecture not supported"
  ^~~~~
make: *** [Makefile:517: tools/mbspc/botlib/be_aas_bspq3.o] Error 1

**Comment by Pollito001** [comment]
i manage to solve this issue, Thanks anyway

**Comment by Garux** [comment]
Thank you, this https://github.com/Garux/netradiant-custom/commit/b75d061ff07a029db3b637ed8109920f9af229d0 will fix it i think.

**Comment by Pollito001** [comment]
Keep doing a great work, I love this version on netradiant.
