### ISSUE TITLE
What is AutoCaulk?

### ISSUE THREAD

**Issue by HeadClot** [Garux/netradiant-custom#25]
Hey,
I was going through the feature list and I saw a feature called autocaulk.

What is it?

**Comment by Garux** [comment]
is explained in the recent release log  
https://github.com/Garux/netradiant-custom/releases/tag/20190705
`Brush->AutoCaulk Selected (F4); camera must be there, where legit player respawn could be, i.e. close to selection and not inside of a brush`

**Comment by Garux** [comment]
is explained in the recent release log
https://github.com/Garux/netradiant-custom/releases/tag/20190705
`Brush->AutoCaulk Selected (F4); camera must be there, where legit player respawn could be, i.e. close to selection and not inside of a brush`  
caulks faces, you'd like to caulk, if caulking manually

**Comment by HeadClot** [comment]
Hey thanks for the info @Garux
