### ISSUE TITLE
How to turn off brush selection planes?

### ISSUE THREAD

**Issue by jsbaboon** [Garux/netradiant-custom#26]
Its very confusing.

I like the rest of your hard work so far.

**Comment by Garux** [comment]
if you mean this: https://imgur.com/S9ratEt - menu.view.show.3d workzone  
This is a must for objects creation/moving/resizing in 3d camera.

**Comment by jsbaboon** [comment]
Yes, although there more rungs than in the example.  I will use previous version for resizing etc, if no option.

**Comment by jsbaboon** [comment]
Scrap last comment. Show 3d fixed it. Thanks

**Comment by Garux** [comment]
Screenshot and system specs would have explained better. So far the feature is know as bugged with some intel video cards or drivers.
