### ISSUE TITLE
Idea: restore default keyboard shortcuts

### ISSUE THREAD

**Issue by The-Gig** [Garux/netradiant-custom#30]
Hi. We already mentioned this on Discord, I just open this "issue" to have it in a more handy place.

One of the nice features of NetRadiant Custom is the ability to easily customize keyboard shortcuts.
But considering it's also easy to make a mess doing it, it may be nice to have the ability to restore things to default.
While it is possible to relatively easily restore all binding defaults by manually deleting **shortcuts.ini** file, not everybody may think about that, and it's an "all-or-nothing" thing.

So, I think it may be useful to have _a button which would allow to reset only the highlighted command to its default key_. In case that key (or key combination) is already used by some other command, it should show the dialog window to choose what to do, just like you changed it normally.

Maybe a further evolution may be, in case one clicks the button with no command selected, ask for confirm to reset ALL keys at once, but that's not as important I think.

**Comment by Garux** [comment]
Such functionality wouldn't be excess i think. Shall need to additionally store default values somewhere, as they are only known at startup atm.

Btw, individual shortcuts are resettable by deletion of respective line in shortcuts.ini, they will get default value during initialisation then, but w/o 'already in use' check.

**Comment by Fruity-0** [comment]
A similar type of question.
How can I back up the settings of the "Radiant" editor (or where are the files responsible for it ...) among others, global settings, colors and theme to copy and overwrite the settings after the computer format and installation?

**Comment by Garux** [comment]
@Fruity-0 changelog-custom.txt from releases:
```glsl
Q: where do editor settings live?
A: radiant/settings folder; they are portable; delete folder to use global OS settings
```

**Comment by Garux** [comment]
Closed by
https://github.com/Garux/netradiant-custom/commit/e25f67ca299797fdbe60569dcaa9273de9852bd8
https://github.com/Garux/netradiant-custom/commit/64e2eebfb3850c3273bdb36cb2a982c6e64bddf2
https://github.com/Garux/netradiant-custom/commit/e301fce02ee8a781b0f2b469dbb3138ebfe4571f
https://github.com/Garux/netradiant-custom/commit/b122d19ec71a4fb0bbf0d3094330106c0b59158c
https://github.com/Garux/netradiant-custom/commit/a4b61f88e5897a9d6151021d4bd9452f149c7f92
