### ISSUE TITLE
Compiling need help have some issues that i hope i can get help with

### ISSUE THREAD

**Issue by RPIWS** [Garux/netradiant-custom#33]
Hello im compiling this on an arm device and get this error message:

`tools/mbspc/botlib/../qcommon/q_platform.h:311:2: error: #error "Architecture not supported"
 #error "Architecture not supported"`

im guessing its possible to fix this as i have compiled netradiant on arm before, any idea? :D

SIncerally
Ztealmax

*** UPDATE ***
Commit: aa44982 worked thanx you

**Comment by Garux** [comment]
Hi, i think this should help https://github.com/Garux/netradiant-custom/commit/aa44982b20f1675815c9542c1344e6d24282f1b7  
Alternatively you can choose to compile only wanted utilities (though ability to compile .aas feels like good addition).
