### ISSUE TITLE
Texture transparency

### ISSUE THREAD

**Issue by Fruity-0** [Garux/netradiant-custom#36]
Hello.
Is it possible to turn off texture transparency (common) in the 3D window and why only some textures are transparent?
I can hardly see the borders of the brushes.

![Screenshot_1](https://user-images.githubusercontent.com/31104533/76705398-1341ac80-66e0-11ea-9d17-4fcc2ef46731.jpg)

![Screenshot_2](https://user-images.githubusercontent.com/31104533/76705408-23598c00-66e0-11ea-94fe-2babf105bf59.jpg)

**Comment by Garux** [comment]
This is not how it's supposed to look like, unless you modified caulk shader.  
Is probably even your video driver bug.  
What's going on actually? As far, as i can see, selected faces of caulk are rendered behind unselected. Is it the only problem? Don't `selected faces wire`, `colorize selection` options affect behavior?  
2nd figure looks almost alright, except there should be stipple for hidden part:
![image](https://user-images.githubusercontent.com/1734117/76721678-d6ae9900-6751-11ea-8440-906951420255.png)
reproduced behavior by adding qer_trans 0.99 to caulk shader:
![image](https://user-images.githubusercontent.com/1734117/76721896-969be600-6752-11ea-8b9e-d47ddfc1692f.png)

**Comment by Fruity-0** [comment]
After a long consultation with specialists , we came to the wrong entry in the "common.shader" file (from my side) and ...
![Screenshot_4](https://user-images.githubusercontent.com/31104533/76794064-8de4f780-67c6-11ea-916a-4ce6c1cba9bc.jpg)

Thanks boys :-D
