### ISSUE TITLE
Very high gamma/washed out orthoview and texture browser on win10 and/or recent nvidia drivers

### ISSUE THREAD

**Issue by KillPixelGames** [Garux/netradiant-custom#38]
This issue is not present on legacy nvidia cards + win7 _or_ AMD cards + win7.

I'm unable to test current nvidia cards with win10 at the moment.

![003](https://user-images.githubusercontent.com/24704461/77110064-5ca13d00-69fb-11ea-9593-57f20d1aee52.jpg)

**Comment by Garux** [comment]
Ought to be worked around in this release https://github.com/Garux/netradiant-custom/releases/tag/20200320

**Comment by KillPixelGames** [comment]
awesome, this fixed the issue!

**Comment by Garux** [comment]
Good to know, thanks
