### ISSUE TITLE
Add support for Tremulous in the releases.

### ISSUE THREAD

**Issue by dGr8LookinSparky** [Garux/netradiant-custom#39]
Hello,

Some Tremulous mappers started to use your netradiant fork relatively recently with good success.  One of those mappers, @BillyRazOr , gave me a .zip of his setup for Tremulous mapping, here is the link with his modifications for your review: https://www.dropbox.com/s/8bnpocvahs6kc08/netradiant-custom-win64.zip?dl=0

Would you include support for Tremulous mapping out of the box in the releases?  If that would be the case, we have some mappers who would be eager in helping out with testing and offer feedback.

**Comment by Garux** [comment]
There are *unverified game configs* linked from readme: https://github.com/Garux/netradiant-custom, Tremulous config is included. Setup is to drop archive contents to radiant folder.  
Idk if that'd be much improvement to include the config in release. Best experience would be with .ent xml entity definitions (enabling smartedit in entity inspector and default values).

**Comment by dGr8LookinSparky** [comment]
I see, from initial browsing, it does look like all of the trem related files in your provided archive matches with what Billy has in his .zip of his setup, so it sounds like the files you provide most likely works as is for trem mapping.  Also I just noticed now that you do have bash scripts for downloading/installing the game packs.  Your current arrangement is pretty straightforward from the looks of it (I should note though that I personally haven't done any mapping yet, so I'm still very much a noob in that area, I have been mainly coding for trem).

Still it might be nice if you had a process to have unverified supported games be determined to be verified and then included directly in the releases, or perhaps have the downloading/installing of the unverified files of a given game built into the program itself, where there would be an option in the menus to install unverified supported games from the unverified archive (part of that would be a drop down menu that lists all of the unverified supported games not yet installed).

**Comment by Garux** [comment]
Gamepacks are downloaded during build process with default settings (not just configs, but also some textures, shaders, models).  
Unverified there stands for 'unmaintained/not polished', however editor runs well with them. I don't think it worth extra complication besides having them at the very start of readme or maintaining + including in releases.

**Comment by BillyRazOr** [comment]
Hi Garux! Nice to meet you! :smile: 
If we made PBR mode for improve textures quality will also support in your netradiant custom? Like rendering from q3map2.

**Comment by Garux** [comment]
Hi, it doesn't sound, like i can handle such task, but what exactly would be wanted from q3map2?  
There is deluxemaps support for such kind of things.

**Comment by BillyRazOr** [comment]
> But what exactly would be wanted from q3map2?

Sorry for late almost a year because I'm too busy for my work, so I'm not often to login GitHub.

PBR stands for "Physically based rendering", it's use for computer graphics to render texture images in any ways that model have flow of lights and looks more realistic or should called "likely in real world". Therefore, it's pretty massive entities and much of structures to approach a modern-look with fancy model.
