### ISSUE TITLE
Origin Brushes for Jedi Academy

### ISSUE THREAD

**Issue by MoritzJT** [Garux/netradiant-custom#43]
"surfaceparm origin" had to be added to the "system.shader" for the origin texture to get it to work properly. This only had "q3map_origin" which wasn't sufficient.

**Comment by ensiform** [comment]
This appears to be a regression in this commit https://github.com/Garux/netradiant-custom/blob/f560e2703b3ccb1cab0f4071ee8c676d8d3f8068/tools/quake3/q3map2/shaders.c looks old, probably netradiant history.

**Comment by Garux** [comment]
Thanks, reenabled that code.
