### ISSUE TITLE
Quake 1 - .pts file loading needs to consider more filepaths

### ISSUE THREAD

**Issue by Kinnuu** [Garux/netradiant-custom#44]
Problem: loading a .pts file only works if the pts file was written to the folder containing the .map file. Compilers however, tend to write the .pts file to the same folder where they write the .bsp file. This is often different to the folder containing the map file.

Solution: The .pts loading should look for the pointfile in the folder where the .bsp was written to first.

**Comment by Garux** [comment]
Problem: radiant has no clue where compiler writes .bsp to.  
Afaik compilers normally write .bsp to .map folder, unless you ask them for something different.

**Comment by Kinnuu** [comment]
Fair enough. I will seek a compiler fix instead.
