### ISSUE TITLE
Allow different color for structural and detail brushes

### ISSUE THREAD

**Issue by ovska** [Garux/netradiant-custom#46]
A simple feature that I miss from using GTK Radiant 1.6.X.
Makes it easier to find leaks and structs where they should not be, as well as get a general layout of the space at a glance.

**Comment by Garux** [comment]
I'v tried this https://s3.amazonaws.com/GtkRadiant/GtkRadiant-1.6.6-20180422.zip from https://icculus.org/gtkradiant/downloads.html to preview the feature, seeing no one.  
I'd don't think it's very worthy feature:
-adds extra colour to 2D colours mess
-display of coincident lines of detail and structural brushes is ambigous
-leaks and structural volumes are previewed way better in 3D
-is not very simple to implement efficiently: would require extra shader for wires or change of this shader to way slower one
-detail filter (ctrl+d) works nuff well for all detailness/structuralness related tasks already

**Comment by ovska** [comment]
Sounds reasonable, I can live with it!
