### ISSUE TITLE
[QUESTION/CURIOSITY] Graphic themes

### ISSUE THREAD

**Issue by Fruity-0** [Garux/netradiant-custom#51]
Good morning.

Noting that NetRadiant supports graphic themes (including my favorite dark ones ...) I figured I could create my own theme for myself and share with others too. Of course, we are talking about a dark theme. It is true that there are a few already on the program, but I would like to do my own. (My eyes refused to obey many times when I was sitting at the monitors for a long time).

And hence my question, Is there any way to create a theme file that is in the "share / themes / ..." directory?

What kind of file is it, is it just bitmaps in certain colors, or maybe compiled (configuration) files with variable RGB values something like an Android application? Or something completely different?

**Comment by Garux** [comment]
There is normally gtkrc text configuration file and sometimes bitmaps.
One way is to copy some theme and customize it.
Googling for `gtk 2 theme creation` finds tutorials on that process and even applications to create a theme.

**Comment by Fruity-0** [comment]
I checked, tested and something starts working ... hurray :-)

Can I, without any copyright consequences, modify any of the available themes under my preferences with a new name, eg: "Radiant Human xxx" and possibly share / send for future appearance in the next editor update?

**Comment by Garux** [comment]
I think yes.

**Comment by Fruity-0** [comment]
Initially I already have a new theme (slightly modified, "still unnamed"), use it and check it out.
In the meantime, I will do some visual tweaks and post on the Discord server.
I think the topic can be closed.
