### ISSUE TITLE
Request for grid sizes beyond 256

### ISSUE THREAD

**Issue by Kinnuu** [Garux/netradiant-custom#52]
I'm working on some gargantuan terrain maps, and would like to be able to set the grid to larger sizes than 256, which is the current maximum. Perhaps adding grid sizes 512, 1024, 2048 and 4096 would be adequate.

**Comment by Garux** [comment]
This looks doable. Not that it has any use in 99.99% of cases.

**Comment by Kinnuu** [comment]
Noted. But it's very useful in enormous (think kilometre-wide) maps when you want to very quickly and accurately move duplicated architectural features into position using the arrow keys, which is what I seem to spend a lot of time doing.

**Comment by Kinnuu** [comment]
I should also add that the scale in my game is different to quake, and some of my buildings have lengths of around 10,000 units, so the current grid size limit of 256 often feels small.
