### ISSUE TITLE
Error running in Manjaro Linux: "undefined symbol: gdk_gl_font_use_pango_font"

### ISSUE THREAD

**Issue by JPLeBreton** [Garux/netradiant-custom#59]
Got this error trying to run the latest release build (downloaded from here, not built myself):

`[netradiant-custom-20200320]$ ./radiant.x86_64`
`./radiant.x86_64: symbol lookup error: ./radiant.x86_64: undefined symbol: gdk_gl_font_use_pango_font`

Pretty sure I have all the needed libraries installed, is this maybe about a deprecated function?

**Comment by ensiform** [comment]
A quick Google search suggests this API was deprecated a long time ago and probably needs to be replaced. Likely Manjaro is using newer build with it fully removed?

**Comment by Garux** [comment]
This is due bitmap fonts support removal from one font library (terminal users tear hairs).  
Text rendering is rewritten in radiant due to this, here is recent linux build: https://www.dropbox.com/s/8wyixkefxwzl2wy/netradiant-custom-20201223-linux-x86_64.7z?dl=1

**Comment by Garux** [comment]
Released fresh builds: https://github.com/Garux/netradiant-custom/releases/tag/20210105, ought to work with new libs.

**Comment by eGax** [comment]
It does and does on Manjaro Linux.
