### ISSUE TITLE
Request for Render lights preview mode for idtech 4 like doom 3

### ISSUE THREAD

**Issue by Pollito001** [Garux/netradiant-custom#60]
That feature is necesary to know how the lights will looks before compile de maps.

**Comment by Garux** [comment]
There is such preview already
![There is such preview already](https://cdn.discordapp.com/attachments/768523802887454730/768524614518702080/17net_rtLight.gif)

**Comment by Pollito001** [comment]
@Garux Thanks for your quick response, Is nice to know that feature is already in the editor.

**Comment by Pollito001** [comment]
Where is that located in the editor?

**Comment by Pollito001** [comment]
@Garux I think it was good idea if you add a button in the GUI for this.

**Comment by Garux** [comment]
There are "TogglePreview" "CameraModeNext" "CameraModePrev" binds for this.

**Comment by Garux** [comment]
Fyi dds loading is broken in 64 bit builds, i'v fixed it just recently.
