### ISSUE TITLE
Feature request: light radius opacity option

### ISSUE THREAD

**Issue by Spaghetti657** [Garux/netradiant-custom#63]
In the camera/3D view, light radiuses tend to get in the way (especially bad if you are trying to work with many together). It would be nice to either have the radius more transparent so you can still see the environment or an option to adjust opacity in preferences.

![lightradius](https://user-images.githubusercontent.com/15520009/109370064-03bd6400-785c-11eb-922b-3a5964138660.jpg)

**Comment by Garux** [comment]
Alright, this the problem indeed.  
It was designed to display radius of single light clearly for resizing in 3D view, also considering possibility of non normalized light colour. It works fine for this purpose, not for multiple lights tho.
Idk what is perfect solution for this; it's using additive blending atm, prolly alpha would work better for multiple lights; also can try to normalize colour, if q3map2 normalizes it anyway.
