### ISSUE TITLE
Wrong common shaders used / game configuration ignored

### ISSUE THREAD

**Issue by Spaghetti657** [Garux/netradiant-custom#64]
Some games (e.g. Jedi Academy) do not use textures/common for core editor shaders and instead use textures/system. This is properly defined in the .game configuration, but netradiant ignores this and always assumes the common path for certain operations (automatic caulking, applying trigger when creating a trigger, possibly others but those are what I am aware of).
![image](https://user-images.githubusercontent.com/15520009/110145952-36ed7f00-7d97-11eb-883d-fb09e865c031.png)

Secondly, it would be nice to be able to turn off the automatic application of the trigger shader on entity creation (for cases where the mapper wants to use a custom one), just like there is an option to turn off automatic caulking.

**Comment by Garux** [comment]
.game cfg definitely works here
![image](https://user-images.githubusercontent.com/1734117/110164935-2672ee00-7e03-11eb-9d11-1f68aeebb1cf.png)
Off option is not very necessary i think, as the mapper will apply custom texture, as he would do with the option.
One improvement there may be using .game `common_shaders_dir="common/"` in GetCommonShader() as a fallback before using hardcoded path to simplify configuration.

**Comment by Spaghetti657** [comment]
The ja.game does not have a shader_trigger entry so that would explain it. Using the configured shaders directory would be a welcome change though.

**Comment by Garux** [comment]
Addressed this 
![image](https://user-images.githubusercontent.com/1734117/111032473-75311100-841d-11eb-9073-f6e25b32d8f8.png)
