### ISSUE TITLE
Feature request: support for the CoD series

### ISSUE THREAD

**Issue by Rex109** [Garux/netradiant-custom#70]
Would it ever be possible to build a config for the cod series (CoD4, WaW, BO1, etc...)? If so i would really love to edit my maps with this radiant.
Or is there a tutorial of how to build a config for a specific game out there?

Thanks in advance!

**Comment by Garux** [comment]
From what i know CoD has own formats of maps, game packages, curves, meshes, textures and models.
Thus CoD maps are not editable in this radiant w/o coding all these features, at least not conveniently.
#31

**Comment by Rex109** [comment]
> From what i know CoD has own formats of maps, game packages, curves, meshes, textures and models.
> Thus CoD maps are not editable in this radiant w/o coding all these features, at least not conveniently.
> #31

Apparently yeah, altough map files seems really easy to read. [PyCoD](https://github.com/SE2Dev/PyCoD) can import compiled xmodels so i don't personally think would be a big deal to reverse the xmodels formats and stuff

**Comment by The-Gig** [comment]
I never played any COD game, but it looks like there is a GTKRadiant fork for COD maybe known simply as Radiant...
<https://callofduty.fandom.com/wiki/Radiant>
<http://modsreloaded.com/call-of-duty-radiant/>
<https://wiki.zeroy.com/index.php?title=Call_of_Duty_:_Radiant_Guide>
Wondering if its source code is available somewhere and might be used to backport something...

**Comment by ensiform** [comment]
It's source code isn't available for free, no. It's proprietary. And afaik the formats after waw/4 are significantly too different. BSP isn't used anymore for example in last few games.

**Comment by Garux** [comment]
There is fresh CoD4 radiant here https://github.com/xoxor4d/iw3xo-radiant, idk how much cool is it.

**Comment by Rex109** [comment]
> There is fresh CoD4 radiant here https://github.com/xoxor4d/iw3xo-radiant, idk how much cool is it.

I personally already use it, but it's no difference between the original one other than bug fixing and live link with cod4
