### ISSUE TITLE
Fix for jk2 and jka system shaders

### ISSUE THREAD

**Issue by CansecoDev** [Garux/netradiant-custom#72]
Both jk2 and jka use `system/trigger` for triggers and `system/caulk` for caulk, this should be added to the gamepacks.

Also `nodraw` could be added but I don't know any use case to test it.

[games.zip](https://github.com/Garux/netradiant-custom/files/6558826/games.zip) (fixed .game fiedls)

**Comment by ensiform** [comment]
Caulk is included as common/caulk anyway in the original game packs under the system.shader file

**Comment by Garux** [comment]
I've addressed this in [wip version](https://www.dropbox.com/s/uqq46o8grlrolu4/netradiant-custom-wip.7z?dl=1) here https://github.com/Garux/netradiant-custom/commit/c0c9f494330947a8adc4990e5582d03dc9f4baa0 after this https://github.com/Garux/netradiant-custom/issues/64 issue, so no gamepack modification is required.
