### ISSUE TITLE
Behaviour request: Deselect objects when changing editing mode

### ISSUE THREAD

**Issue by germangar** [Garux/netradiant-custom#73]
When changing from object mode to face/edge/vertex mode the former mode selection remains selected. It is a bit annoying when you forget to deselect before changing because you can end up with both the brush and a face/etc selected so you have to deselect all. It's a minor thing, but it would feel better if changed.

I don't think there is any use for having hybrid selections? I've never had a need for it, at least.

It probably shouldn't deselect right at changing, but at selecting the first thing in the new mode.

**Comment by Garux** [comment]
Unsure if i follow, it's designed to only edit components of selected objects. You can't even enter component mode w/o object selection, deselection disables component mode automatically too.

**Comment by germangar** [comment]
Doesn't matter. BTW, here you have a couple of minor q3map2 fixes. It probably would be a good thing to revise all the data in the game descriptors is apllied at initialization, cause it seems a bunch of them aren't. It's three already that I catched and I'm not even looking for it.

* Fix: Do not ignore game descriptor value for maxLMSurfaceVerts and keepLights
Use unsigned int for maxLMSurfaceVerts, maxSurfaceVerts and maxSurfaceIndexes
Fix: Out of bounds value at qfusion.h

[ncr-minifixes.zip](https://github.com/Garux/netradiant-custom/files/6583785/ncr-minifixes.zip)
