### ISSUE TITLE
Tiny font size in 2D/Camera windows

### ISSUE THREAD

**Issue by negke** [Garux/netradiant-custom#75]
The text in the 2D and camera windows (brush/entity selection size, class and target names) is so small, it's barely readable on my resolution. It used to be fine, but then I reinstalled Windows 10 and some text scale setting it previously had must have been reset (or different, no idea how I did it before). I use 1920x1080 and apparently a custom scale of 115%. In Netradiant, the menus are fine, but the custom scale does not affect the text inside those windows. Could be another case of outdated SDK stuff? It's not a super critical issue, but it would nice if there was a way to increase the text size. I would have expected "Misc/Colors/OpenGL font" did that, but it seems it only affects the grid numbers.

**Comment by negke** [comment]
Never mind. It seems OpenGL font does actually work - except for the classnames and targetnames.

**Comment by Garux** [comment]
Actually works for them too, after map reloading. Default font size is supposed to be okay in full hd w/o scaling.
