### ISSUE TITLE
Constant crashes on Win10

### ISSUE THREAD

**Issue by wolfetplayer** [Garux/netradiant-custom#76]
[radiant.log](https://github.com/Garux/netradiant-custom/files/6604529/radiant.log)

As title say there are constant crashes on 64x build of Netradiant.
I'm just trying to grab anything in 3D view and it crashes. 
Log is above.

**Comment by wolfetplayer** [comment]
[radiant.log](https://github.com/Garux/netradiant-custom/files/6604533/radiant.log)
This is log from when it crashes while loading textures.

**Comment by wolfetplayer** [comment]
Forgot to mention - the crashing issue only persist on my win10 home PC.
It is working fine on my old laptop with win7 aboard.

**Comment by Garux** [comment]
From description problem looks related to rendering text in viewports (sizing info in 3D, texture names in tex bro).
Though i suspect that 2D grid coordinates and entity names are okay 🤔
Does this also happen in newer release?

**Comment by Garux** [comment]
Both these cases also use opengl stipple (3D for hidden wire, tex bro for shaders), can verify by selecting in 3D in wireframe rendermode.

**Comment by wolfetplayer** [comment]
The crash I mentioned in the first post seems to be fixed in the recent build(5 jan build, second post crash). However it still leaves me with texture folder crash

**Comment by Garux** [comment]
This smells more like memory corruption then, nobody else experiences.
Just tried given release with RTCW (2001 binaries) @ win10, nvidia 4.6, loaded all textures w/o issues.

**Comment by wolfetplayer** [comment]
You mean like hardware RAM issues?
Kinda weird that it is affecting only q3 based radiants.

**Comment by Garux** [comment]
No, corruption by the code, which in turn results in floating error.
But do you say other radiants have same issue? Might be opengl driver problem then, for which i can make debug build.

**Comment by wolfetplayer** [comment]
Yeah, all q3 based radiants have similar crashes. d3 radiant works fine

**Comment by Garux** [comment]
This no good. Radiants differ much, so some very general instruction causes the problem @ your environment.
Here is debug build https://www.dropbox.com/s/s56n2jr6jy5x540/netradiant-custom-wip_debug.7z?dl=1, gotta report opengl issues, if any.
Also looking at possibility to debug minidump @ windows + gcc.

**Comment by Garux** [comment]
Or possibly some specific data in your game folder causes memory corruption, showing the effect later.
Best test would be with hbarebones OS and game.

**Comment by Garux** [comment]
Okay, now i can look at crash dump, if you enable them (https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps) and send .dmp file.

**Comment by wolfetplayer** [comment]
Sorry for reviving this. But I just cant to crash this debug build. Maybe it was fixed somewhere in the post-january(last build) commits?

Can you please compile the most recent non-debug win x64 version for me please?
I'm having a hard time compiling it on my own. Thanks in advance.

**Comment by Garux** [comment]
https://www.dropbox.com/s/uqq46o8grlrolu4/netradiant-custom-wip.7z?dl=1

**Comment by wolfetplayer** [comment]
Did a clean OS install. Still randomly crashes. Maybe it is some kind of GPU drivers incompatibility? (i got Geforce RTX 2070 Super)
[radiant.log](https://github.com/Garux/netradiant-custom/files/7272927/radiant.log)
.

**Comment by Garux** [comment]
Can be anything literally. Decent debugging would be getting .dmp with debug build, but it doesn't crash for you.
There are many things to try in problem environment to figure out problem quickly, it's just tedious in such remote manner.
One invariant in your experiment is the game and a few .pk3s. Can you try with e.g. fresh Q3 install to ensure, that it's about something else?
