### ISSUE TITLE
Quake 1 - missing models for health, ammo, DM maps causing precaching errors on map load

### ISSUE THREAD

**Issue by Fat-Angus** [Garux/netradiant-custom#81]
So far this editor has been great - in terms of usage it's the best Quake 1 editor around.  Problem is, models for health and ammo aren't showing in either the camera view or orthographic views - all that I get are small black and blue cubes with an offset bounding box.  And whenever I run a map in deathmatch mode I am greeted by numerous non precached errors (CTD with Quakespasm, Console errors in Darkplaces, and ezQuake won't run at all).  Are these two linked?  I can play the map in single player, but running it in deathmatch causes the previous errors.

**Comment by Garux** [comment]
There is `q1pack` folder with explanation txt, making these models visible in editor.
The second issue is unknown for me and is not related to ineditor models display.

**Comment by eGax** [comment]
It might help to share your `*.map` so someone could maybe take a look, maybe compile and run themselves to see if the same errors occur.

**Comment by Fat-Angus** [comment]
We finally found the problem.  It was because the worldspawn had a spawnflag attributed to it.
