### ISSUE TITLE
Spawnflags limited to 16 unique flags

### ISSUE THREAD

**Issue by wongit** [Garux/netradiant-custom#82]
Currently not possible to use more than 16 spawnflags in an entity file without getting invalid bit error.

**Comment by Garux** [comment]
Yeah, it's limited to 16 https://github.com/Garux/netradiant-custom/blob/master/include/ieclass.h#L31
I don't think anything practical uses > 16.

**Comment by wongit** [comment]
Trenchbroom is using 24 I think. Some recent quake mods are preferring to use spawnflags over keys so it can creep over 16.
Compiled with 24 and seems to be working. Thanks for the infos
