### ISSUE TITLE
Unable to set brushes to be "detail" instead of "structural" for Quake 2

### ISSUE THREAD

**Issue by motorsep** [Garux/netradiant-custom#83]
That "detail" flag is always grayed out no matter what brush I select.

![image](https://user-images.githubusercontent.com/1927918/127786454-b3f50453-15d0-49c5-8c8b-74aee159a9ce.png)

Could you please fix that? Thanks

**Comment by Garux** [comment]
It is intentionally grayed out here https://github.com/Garux/netradiant-custom/blob/master/radiant/surfacedialog.cpp#L1192. Probably for some good reason? I don't know. Brush.make detail/structural set correct flags.

**Comment by motorsep** [comment]
All good!
