### ISSUE TITLE
Crashing on maximise/resize window (latest alpha)

### ISSUE THREAD

**Issue by LDAsh72** [Garux/netradiant-custom#88]
The program itself seems to work fine after launching, I can drag brushes and load maps, etc, but it crashes when trying to maximise or resize.  Minimising is fine, moving the window is fine, and resizing other things like surface inspector is fine.  It also crashes when changing the theme, so maybe a GTK issue?  Previous (20210105) version works fine.
Running Windows 7 64bit on a Lenovo Thinkpad X200 Tablet.
.
.
.

**Comment by Garux** [comment]
You imply `Development Build` i guess. Got no named problems here @ win10. Probably newer gtk version + older win is the problem.
This is up-to-date build with libs, used in release (older): https://www.dropbox.com/s/uqq46o8grlrolu4/netradiant-custom-wip.7z?dl=1

**Comment by LDAsh72** [comment]
Fair enough, if you're making a deliberate decision to not support anything lower than Win10.  It is that season.
I suppose I could get it maximised and set the theme by poking around its config files, local.pref?  I'm sure I can get around it that way and still enjoy your efforts.

**Comment by Garux** [comment]
The other guy got crash of Development Build on choosing specific theme @ win10, i have no either of issues @ win10.
This is not decision to only support win10+, looks sooner like problems with gtk version, used in github's autobuild.
You can tweak theme and maximization via configs, but i suspect there will be more problems with this build, so i suggest to try linked wip build instead. Gonna stick to gtk version, used there, for releases, as it's known as working

**Comment by Garux** [comment]
Wasn't there anything in `radiant.log` before crash? (to not accuse gtk version blindly)

**Comment by LDAsh72** [comment]
Good call.  I don't think so:-
https://www.violae.net/temp/radiant_log.txt

**Comment by Garux** [comment]
This must have been changed in Qt https://github.com/Garux/netradiant-custom/commit/9d3d2040182af8284fe9c6fdf26950cfa738c4f2, autobuilds look more decent too.
