### ISSUE TITLE
Expected behavior regarding brush solidity

### ISSUE THREAD

**Issue by decldev** [Garux/netradiant-custom#90]
Having one side of a brush painted with nodrawnonsolid makes whole brush nonsolid. This does not happen in official netradiant release.

Which one is correct?

**Comment by ensiform** [comment]
Older versions of radiant mainly gtk and I don't know about the non custom netradiant, but GTK saves faces at random and q3map2 in those versions only look at the first face for the brush surface.

**Comment by decldev** [comment]
> Older versions of radiant mainly gtk and I don't know about the non custom netradiant, but GTK saves faces at random and q3map2 in those versions only look at the first face for the brush surface.

This might be it then. Official Xonotic maps have grating's sides painted with nodrawnonsolid and I dropped through when I built them with netradiant-custom.

**Comment by ensiform** [comment]
The correct thing would be to use a matching solid invisible/common shader. Not nonsolid
