### ISSUE TITLE
mbspc - entity issues

### ISSUE THREAD

**Issue by BlackShadow** [Garux/netradiant-custom#92]
Entity brushes decompiled with multiple faces and texture alligment issues.

For example this trigger has many faces:

![image](https://user-images.githubusercontent.com/30868395/154185181-cc42c68c-dcae-4a97-b8de-76754dd7598b.png)

Original brush:

![image](https://user-images.githubusercontent.com/30868395/154185224-65bb88ae-630c-41fa-8864-b411b313996a.png)

Fence texture replaced with that green box texture.

![image](https://user-images.githubusercontent.com/30868395/154185517-faf3d371-8943-4197-8b2f-548dd706b13c.png)

Door texture replaced by some stone texture

![image](https://user-images.githubusercontent.com/30868395/154185558-6aa1dc99-379f-4d24-8253-ab2654bf6f41.png)

Map Crossfire - HL1

**Comment by BlackShadow** [comment]
There's a another decompiler for Goldsource called BS2Map. It creates brush trigger really close to original. Geometry a bit flawed but not bad results.

**Comment by BlackShadow** [comment]
There's a another decompiler for Goldsource called BSP2Map. It creates trigger brushes really close to original. Geometry is a bit flawed but not bad results.

**Comment by Garux** [comment]
I need original .map file (not .bsp) to ease check of what's wrong.

**Comment by BlackShadow** [comment]
Oh sorry, here.

Although this is not the original map file for that map, it's the closest one you can find to the original. Brushes and geometry all of them uncompiled. (Except one small part)

[crossfire.zip](https://github.com/Garux/netradiant-custom/files/8102742/crossfire.zip)

**Comment by Garux** [comment]
Addressed shown issues, algorithm implementation was not quite correct.
Can test with autobuild binaries https://github.com/Garux/netradiant-custom/releases/tag/latest
