### ISSUE TITLE
question about texturelights

### ISSUE THREAD

**Issue by BlackShadow** [Garux/netradiant-custom#93]
AFAIK texture light data isn't stored in BSP, is there a somehow a way to get/decompile texture light info?

**Comment by Garux** [comment]
Texture light data as in lights.rad, right? Idk either, but sounds pretty unlikely that it's stored somewhere besides the effect on lightmaps.

**Comment by BlackShadow** [comment]
Yep light data as in lights.rad BSP doesn't store light data like entities. sadly  Thought you might have some workaround.
