### ISSUE TITLE
Is it possible to recreate original geometry?

### ISSUE THREAD

**Issue by BlackShadow** [Garux/netradiant-custom#94]
mbspc decompiles map with extra brushes. Is it possible to decompile like in original?
original:

![image](https://user-images.githubusercontent.com/30868395/154821197-f33d08c5-b4c3-4f91-9f7a-b1ae954cbedf.png)

mbspc
![image](https://user-images.githubusercontent.com/30868395/154821173-08e94674-c051-40e5-af98-b360fa8b82ed.png)

**Comment by Garux** [comment]
Noticed this too, must be possible to avoid. I haven't written this code however, thus not a simple journey.

**Comment by BlackShadow** [comment]
Hey @Garux 

How you been? After 1 year later, any progress with your decompiler so far? 🙂

**Comment by Garux** [comment]
No, haven't looked into this yet.

**Comment by Garux** [comment]
Looking at this more, isn't it HL compiler prolongating brushes to fill map's volume? Because such thing doesn't happen, when decompiling Q1 maps.

**Comment by Garux** [comment]
https://github.com/Garux/netradiant-custom/blob/6fa7a8b5bd8abdf583111370d4a48a9b865f422e/tools/mbspc/mbspc/map_hl.c#L462-L466
https://github.com/Garux/netradiant-custom/blob/6fa7a8b5bd8abdf583111370d4a48a9b865f422e/tools/mbspc/mbspc/map_hl.c#L483-L486
https://github.com/Garux/netradiant-custom/blob/6fa7a8b5bd8abdf583111370d4a48a9b865f422e/tools/mbspc/mbspc/map_hl.c#L492-L493
So, replying to your question, this is not possible.
To clarify, they are not extra brushes, but extended normal ones.
