### ISSUE TITLE
Neverball map completely empty after compiling

### ISSUE THREAD

**Issue by Droooga** [Garux/netradiant-custom#95]
it saves the .map alright but the .sol contains no map data. i didn't have these issues in illwieckz's netradiant build though

**Comment by Garux** [comment]
Where does it come from? I vaguely recall something about .sol, but can't find related code in netradiant.
Gamepack is equal to NR, must be running the same custom tools.

**Comment by Droooga** [comment]
the mapc compiler that comes with neverball compiles the .map file to a .sol file, not sure if its mapc having the wrong syntax or radiant itself. i've also noticed that when mapc compiles the map, mapc doesn't find any mtrl, vertices, edges or even sides in the level, but it does find lumps, nodes, bodies and chars.

**Comment by Garux** [comment]
My assumption here is that mapc doesn't support BP map format, which is default in NRC.
Where to alter it and where current map format is shown:
![image](https://user-images.githubusercontent.com/1734117/155202748-3228d24c-af8c-4a0c-b3fb-61ab936cff04.png)

**Comment by Droooga** [comment]
oh, it works now. thanks a lot!
